import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";


export const metadata: Metadata = {
  title: "School Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-row">
        {/* Mount our sidebar so it locks in place permanently */}
        <Sidebar />

        {/* This main frame handles our shifting sub-pages natively */}
        <main className="flex-1 p-8">{children}</main>
      </body>
    </html>
  );
}
